import fs from 'fs';
import path from 'path';
import { ensureDir, getGeneratedDir, getLogsDir } from '../shared/paths';

export const APACHE_SITES_CONF_NAME = 'stacklet-apache.conf';

export function apacheGeneratedDir(): string {
  return path.join(getGeneratedDir(), 'apache');
}
export function apacheSitesConfPath(): string {
  return path.join(apacheGeneratedDir(), APACHE_SITES_CONF_NAME);
}

export interface ApachePaths {
  binary: string;
  serverRoot: string;
  config: string;
}

/** Resolve httpd.exe + ServerRoot + httpd.conf from an Apache install dir. */
export function apachePathsFromInstallRoot(installRoot: string): ApachePaths | null {
  const binary = path.join(installRoot, 'bin', 'httpd.exe');
  if (!fs.existsSync(binary)) return null;
  return {
    binary,
    serverRoot: installRoot,
    config: path.join(installRoot, 'conf', 'httpd.conf'),
  };
}

const REQUIRED_MODULES = [
  'rewrite_module modules/mod_rewrite.so',
  'proxy_module modules/mod_proxy.so',
  'proxy_fcgi_module modules/mod_proxy_fcgi.so',
  'ssl_module modules/mod_ssl.so',
  'socache_shmcb_module modules/mod_socache_shmcb.so',
  'vhost_alias_module modules/mod_vhost_alias.so',
];

const DEVMGR_BEGIN = '# BEGIN devmgr';
const DEVMGR_END = '# END devmgr';

/**
 * Patch Apache Lounge's shipped conf/httpd.conf for Stacklet: point ServerRoot
 * at the install dir, enable the modules we need (mod_proxy_fcgi proxies PHP to
 * the existing php-cgi on 127.0.0.1:9000), and include our generated vhosts.
 * PHP itself is reused from the php-fpm runtime — no mod_php needed.
 */
export function configureApacheInstall(installRoot: string): void {
  const confPath = path.join(installRoot, 'conf', 'httpd.conf');
  if (!fs.existsSync(confPath)) return;

  let content = fs.readFileSync(confPath, 'utf8');
  const fwd = installRoot.replace(/\\/g, '/');

  // 1. Point SRVROOT / ServerRoot at the actual install dir.
  content = content.replace(/^Define SRVROOT ".*"$/m, `Define SRVROOT "${fwd}"`);
  if (!/^Define SRVROOT /m.test(content)) {
    content = `Define SRVROOT "${fwd}"\n${content}`;
  }
  content = content.replace(/^ServerRoot ".*"$/m, 'ServerRoot "${SRVROOT}"');

  // 2. Enable required modules (uncomment if present).
  for (const mod of REQUIRED_MODULES) {
    const re = new RegExp(`^#\\s*LoadModule\\s+${mod.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`, 'm');
    content = content.replace(re, `LoadModule ${mod}`);
  }

  // 3. Quiet ServerName warning.
  if (!/^ServerName /m.test(content)) {
    content = content.replace(/^#ServerName .*$/m, 'ServerName localhost:80');
  }

  // 4. Replace/append the devmgr include block (idempotent).
  ensureDir(apacheGeneratedDir());
  if (!fs.existsSync(apacheSitesConfPath())) {
    fs.writeFileSync(apacheSitesConfPath(), '# Generated by Stacklet — Apache site vhosts\n', 'utf8');
  }
  ensureDir(path.join(getLogsDir(), 'apache'));
  const includeBlock = [
    DEVMGR_BEGIN,
    // httpd.conf already has "Listen 80"; add 443 for the SSL vhosts.
    'Listen 443',
    `Include "${apacheSitesConfPath().replace(/\\/g, '/')}"`,
    DEVMGR_END,
  ].join('\n');
  const blockRe = new RegExp(`${DEVMGR_BEGIN}[\\s\\S]*?${DEVMGR_END}`, 'm');
  content = blockRe.test(content)
    ? content.replace(blockRe, includeBlock)
    : `${content.trimEnd()}\n\n${includeBlock}\n`;

  fs.writeFileSync(confPath, content, 'utf8');
}
