import fs from 'fs';
import path from 'path';
import type { MysqlIniOptions } from '../config/types';

export const MYSQL_INI_KEYS = [
  'max_connections',
  'innodb_buffer_pool_size',
  'max_allowed_packet',
  'character_set_server',
  'collation_server',
  'sql_mode',
  'slow_query_log',
  'long_query_time',
  'general_log',
] as const;

export type MysqlIniKey = (typeof MYSQL_INI_KEYS)[number];

export function defaultMysqlIniOptions(): MysqlIniOptions {
  return {
    max_connections: 151,
    innodb_buffer_pool_size: '128M',
    max_allowed_packet: '64M',
    character_set_server: 'utf8mb4',
    collation_server: 'utf8mb4_unicode_ci',
    sql_mode: 'STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION',
    slow_query_log: false,
    long_query_time: 2,
    general_log: false,
  };
}

export function mergeMysqlIniOptions(partial?: Partial<MysqlIniOptions>): MysqlIniOptions {
  return { ...defaultMysqlIniOptions(), ...partial };
}

/** Windows-friendly paths for my.ini (forward slashes). */
function iniPathValue(p: string): string {
  return path.resolve(p).replace(/\\/g, '/');
}

function formatIniValue(key: MysqlIniKey, value: string | number | boolean): string {
  if (key === 'slow_query_log' || key === 'general_log') {
    return value === true || value === '1' || value === 1 ? '1' : '0';
  }
  return String(value);
}

export function myIniPath(installRoot: string): string {
  return path.join(installRoot, 'my.ini');
}

export function renderMyIniContent(
  installRoot: string,
  dataDir: string,
  port: number,
  options: MysqlIniOptions,
): string {
  const shareDir = path.join(installRoot, 'share');
  const lcMessages = fs.existsSync(shareDir)
    ? `lc-messages-dir=${iniPathValue(shareDir)}\n`
    : '';

  const lines = [
    '# Generated by dev-mgr — edit via Settings or this file',
    '[mysqld]',
    `basedir=${iniPathValue(installRoot)}`,
    `datadir=${iniPathValue(dataDir)}`,
    `port=${port}`,
    'bind-address=127.0.0.1',
    lcMessages.trimEnd(),
    'skip-name-resolve',
    `max_connections=${options.max_connections}`,
    `innodb_buffer_pool_size=${options.innodb_buffer_pool_size}`,
    `max_allowed_packet=${options.max_allowed_packet}`,
    `character-set-server=${options.character_set_server}`,
    `collation-server=${options.collation_server}`,
    `sql_mode=${options.sql_mode}`,
    `slow_query_log=${formatIniValue('slow_query_log', options.slow_query_log)}`,
    `long_query_time=${options.long_query_time}`,
    `general_log=${formatIniValue('general_log', options.general_log)}`,
    'default-storage-engine=InnoDB',
    '',
    '[client]',
    `port=${port}`,
    'host=127.0.0.1',
    'user=root',
    'password=',
    '',
  ];

  return lines.filter((line, i, arr) => !(line === '' && arr[i - 1] === '')).join('\n');
}

export function writeMyIni(
  installRoot: string,
  dataDir: string,
  port: number,
  options?: Partial<MysqlIniOptions>,
): string {
  const file = myIniPath(installRoot);
  const merged = mergeMysqlIniOptions(options);
  fs.writeFileSync(file, renderMyIniContent(installRoot, dataDir, port, merged), 'utf8');
  return file;
}

function parseIniSection(content: string): Map<string, string> {
  const map = new Map<string, string>();
  for (const raw of content.split(/\r?\n/)) {
    const line = raw.trim();
    if (!line || line.startsWith(';') || line.startsWith('#') || line.startsWith('[')) continue;
    const eq = line.indexOf('=');
    if (eq <= 0) continue;
    const key = line.slice(0, eq).trim().toLowerCase().replace(/-/g, '_');
    const value = line.slice(eq + 1).trim();
    map.set(key, value);
  }
  return map;
}

export function readMysqlIniOptions(iniPath: string): Partial<MysqlIniOptions> {
  if (!fs.existsSync(iniPath)) return {};
  const parsed = parseIniSection(fs.readFileSync(iniPath, 'utf8'));
  const out: Partial<MysqlIniOptions> = {};

  const maxConn = parsed.get('max_connections');
  if (maxConn !== undefined) out.max_connections = Number(maxConn) || defaultMysqlIniOptions().max_connections;

  const buf = parsed.get('innodb_buffer_pool_size');
  if (buf !== undefined) out.innodb_buffer_pool_size = buf;

  const packet = parsed.get('max_allowed_packet');
  if (packet !== undefined) out.max_allowed_packet = packet;

  const charset = parsed.get('character_set_server');
  if (charset !== undefined) out.character_set_server = charset;

  const coll = parsed.get('collation_server');
  if (coll !== undefined) out.collation_server = coll;

  const mode = parsed.get('sql_mode');
  if (mode !== undefined) out.sql_mode = mode;

  const slow = parsed.get('slow_query_log');
  if (slow !== undefined) out.slow_query_log = slow === '1' || slow.toLowerCase() === 'on';

  const longQ = parsed.get('long_query_time');
  if (longQ !== undefined) out.long_query_time = Number(longQ) || defaultMysqlIniOptions().long_query_time;

  const gen = parsed.get('general_log');
  if (gen !== undefined) out.general_log = gen === '1' || gen.toLowerCase() === 'on';

  return out;
}
