import fs from 'fs';
import path from 'path';
import type { NginxOptions } from '../config/types';
import { ensureDir, getGeneratedDir } from '../shared/paths';

export const NGINX_HTTP_CONF_NAME = 'stacklet-http.conf';

export function devMgrHttpConfPath(): string {
  return path.join(getGeneratedDir(), 'nginx', NGINX_HTTP_CONF_NAME);
}

export function defaultNginxOptions(): NginxOptions {
  return {
    /** 0 = no limit (nginx local dev). */
    client_max_body_size: '0',
    keepalive_timeout: 65,
    gzip: true,
    sendfile: true,
    server_names_hash_bucket_size: 64,
    fastcgi_connect_timeout: '60s',
    fastcgi_send_timeout: '300s',
    fastcgi_read_timeout: '300s',
  };
}

export function mergeNginxOptions(partial?: Partial<NginxOptions>): NginxOptions {
  return { ...defaultNginxOptions(), ...partial };
}

/** PHP has no "unlimited" — map nginx 0 to a large cap for php.ini. */
export function phpUploadLimitForNginxBodySize(clientMaxBodySize: string): string {
  if (clientMaxBodySize === '0') return '512M';
  return clientMaxBodySize;
}

export function renderDevMgrHttpConf(options: NginxOptions): string {
  return [
    '# Generated by dev-mgr — http-level tuning',
    `client_max_body_size ${options.client_max_body_size};`,
    `keepalive_timeout ${options.keepalive_timeout};`,
    `gzip ${options.gzip ? 'on' : 'off'};`,
    `sendfile ${options.sendfile ? 'on' : 'off'};`,
    `server_names_hash_bucket_size ${options.server_names_hash_bucket_size};`,
    'fastcgi_buffer_size 128k;',
    'fastcgi_buffers 8 128k;',
    'fastcgi_busy_buffers_size 256k;',
    '',
  ].join('\n');
}

export function writeDevMgrHttpConf(options?: Partial<NginxOptions>): string {
  const file = devMgrHttpConfPath();
  ensureDir(path.dirname(file));
  const merged = mergeNginxOptions(options);
  fs.writeFileSync(file, renderDevMgrHttpConf(merged), 'utf8');
  return file;
}

export function readDevMgrHttpConf(filePath: string): Partial<NginxOptions> {
  if (!fs.existsSync(filePath)) return {};
  const content = fs.readFileSync(filePath, 'utf8');
  const out: Partial<NginxOptions> = {};

  const body = content.match(/client_max_body_size\s+([^;]+);/i);
  if (body) out.client_max_body_size = body[1].trim();

  const keep = content.match(/keepalive_timeout\s+(\d+)/i);
  if (keep) out.keepalive_timeout = Number(keep[1]);

  const gzip = content.match(/gzip\s+(on|off)/i);
  if (gzip) out.gzip = gzip[1].toLowerCase() === 'on';

  const send = content.match(/sendfile\s+(on|off)/i);
  if (send) out.sendfile = send[1].toLowerCase() === 'on';

  const bucket = content.match(/server_names_hash_bucket_size\s+(\d+)/i);
  if (bucket) out.server_names_hash_bucket_size = Number(bucket[1]);

  return out;
}
