import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import type { PhpMyAdminOptions } from '../config/types';

const DEVMGR_MARKER = 'Generated by dev-mgr';

export function defaultPhpMyAdminOptions(mysqlPort = 3306): PhpMyAdminOptions {
  return {
    mysql_host: '127.0.0.1',
    mysql_port: mysqlPort,
    auth_type: 'cookie',
    allow_no_password: true,
    mysql_user: 'root',
    mysql_password: '',
    max_size: '512M',
    memory_limit: '256M',
    exec_time_limit: 300,
    login_cookie_validity: 1440,
    default_lang: 'en',
  };
}

export function mergePhpMyAdminOptions(
  partial?: Partial<PhpMyAdminOptions>,
  mysqlPort = 3306,
): PhpMyAdminOptions {
  return { ...defaultPhpMyAdminOptions(mysqlPort), ...partial };
}

function escapePhpString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
}

function findIndexPhp(root: string): string | null {
  const direct = path.join(root, 'index.php');
  if (fs.existsSync(direct)) return direct;

  for (const entry of fs.readdirSync(root, { withFileTypes: true })) {
    if (!entry.isDirectory()) continue;
    const nested = path.join(root, entry.name, 'index.php');
    if (fs.existsSync(nested)) return nested;
  }
  return null;
}

export function resolvePhpMyAdminRoot(installPath: string): string | null {
  const resolved = path.resolve(installPath);
  if (!fs.existsSync(resolved)) return null;

  const indexPhp = findIndexPhp(resolved);
  if (indexPhp) return path.dirname(indexPhp);
  return null;
}

export function phpMyAdminConfigPath(installPath: string): string | null {
  const root = resolvePhpMyAdminRoot(installPath);
  if (!root) return null;
  return path.join(root, 'config.inc.php');
}

function readBlowfishSecret(configFile: string): string {
  if (!fs.existsSync(configFile)) return crypto.randomBytes(16).toString('hex');
  const existing = fs.readFileSync(configFile, 'utf8');
  const match = existing.match(/['"]blowfish_secret['"]\s*=\s*['"]([^'"]+)['"]/);
  return match?.[1] ?? crypto.randomBytes(16).toString('hex');
}

function parsePhpConfigValue(raw: string): string | number | boolean {
  const v = raw.trim();
  if (/^(true|false)$/i.test(v)) return v.toLowerCase() === 'true';
  if (/^\d+$/.test(v)) return Number(v);
  const quoted = v.match(/^['"](.*)['"]$/);
  if (quoted) return quoted[1];
  return v;
}

export function readPhpMyAdminOptions(configFile: string): Partial<PhpMyAdminOptions> {
  if (!fs.existsSync(configFile)) return {};
  const content = fs.readFileSync(configFile, 'utf8');
  const out: Partial<PhpMyAdminOptions> = {};

  const host = content.match(/\['host'\]\s*=\s*([^;]+);/);
  if (host) out.mysql_host = String(parsePhpConfigValue(host[1]));

  const port = content.match(/\['port'\]\s*=\s*([^;]+);/);
  if (port) out.mysql_port = Number(parsePhpConfigValue(port[1]));

  const auth = content.match(/\['auth_type'\]\s*=\s*([^;]+);/);
  if (auth) {
    const t = String(parsePhpConfigValue(auth[1]));
    if (t === 'cookie' || t === 'config') out.auth_type = t;
  }

  const noPass = content.match(/\['AllowNoPassword'\]\s*=\s*([^;]+);/);
  if (noPass) out.allow_no_password = Boolean(parsePhpConfigValue(noPass[1]));

  const user = content.match(/\['user'\]\s*=\s*([^;]+);/);
  if (user) out.mysql_user = String(parsePhpConfigValue(user[1]));

  const pass = content.match(/\['password'\]\s*=\s*([^;]+);/);
  if (pass) out.mysql_password = String(parsePhpConfigValue(pass[1]));

  const maxSize = content.match(/\$cfg\['MaxSize'\]\s*=\s*([^;]+);/);
  if (maxSize) out.max_size = String(parsePhpConfigValue(maxSize[1]));

  const mem = content.match(/\$cfg\['MemoryLimit'\]\s*=\s*([^;]+);/);
  if (mem) out.memory_limit = String(parsePhpConfigValue(mem[1]));

  const exec = content.match(/\$cfg\['ExecTimeLimit'\]\s*=\s*([^;]+);/);
  if (exec) out.exec_time_limit = Number(parsePhpConfigValue(exec[1]));

  const cookie = content.match(/\$cfg\['LoginCookieValidity'\]\s*=\s*([^;]+);/);
  if (cookie) out.login_cookie_validity = Number(parsePhpConfigValue(cookie[1]));

  const lang = content.match(/\$cfg\['DefaultLang'\]\s*=\s*([^;]+);/);
  if (lang) out.default_lang = String(parsePhpConfigValue(lang[1]));

  return out;
}

export function renderPhpMyAdminConfigContent(
  options: PhpMyAdminOptions,
  blowfishSecret: string,
): string {
  const serverLines = [
    `$cfg['Servers'][$i]['auth_type'] = '${escapePhpString(options.auth_type)}';`,
    `$cfg['Servers'][$i]['host'] = '${escapePhpString(options.mysql_host)}';`,
    `$cfg['Servers'][$i]['port'] = '${options.mysql_port}';`,
    `$cfg['Servers'][$i]['connect_type'] = 'tcp';`,
    `$cfg['Servers'][$i]['compress'] = false;`,
    `$cfg['Servers'][$i]['AllowNoPassword'] = ${options.allow_no_password ? 'true' : 'false'};`,
    `$cfg['Servers'][$i]['extension'] = 'mysqli';`,
  ];

  if (options.auth_type === 'config') {
    serverLines.push(
      `$cfg['Servers'][$i]['user'] = '${escapePhpString(options.mysql_user)}';`,
      `$cfg['Servers'][$i]['password'] = '${escapePhpString(options.mysql_password)}';`,
    );
  }

  return `<?php
/**
 * ${DEVMGR_MARKER} for local development only.
 */
$cfg['blowfish_secret'] = '${escapePhpString(blowfishSecret)}';
$cfg['DefaultLang'] = '${escapePhpString(options.default_lang)}';
$cfg['MaxSize'] = '${escapePhpString(options.max_size)}';
$cfg['MemoryLimit'] = '${escapePhpString(options.memory_limit)}';
$cfg['ExecTimeLimit'] = ${options.exec_time_limit};
$cfg['LoginCookieValidity'] = ${options.login_cookie_validity};

$i = 0;
$i++;
${serverLines.join('\n')}
`;
}

/** Local-dev phpMyAdmin config: MariaDB on 127.0.0.1, empty password allowed by default. */
export function ensurePhpMyAdminConfig(
  installPath: string,
  options?: Partial<PhpMyAdminOptions>,
): boolean {
  const root = resolvePhpMyAdminRoot(installPath);
  if (!root) return false;

  const configFile = path.join(root, 'config.inc.php');
  const merged = mergePhpMyAdminOptions(options, options?.mysql_port ?? 3306);
  const blowfishSecret = readBlowfishSecret(configFile);
  const content = renderPhpMyAdminConfigContent(merged, blowfishSecret);

  fs.writeFileSync(configFile, content, 'utf8');
  return true;
}
