/**
 * Single source of truth for product identity and internal identifiers.
 * Change values here when forking or rebranding Stacklet.
 */

export const BRAND = {
  /** User-facing product name (Settings, tray, window title). */
  name: 'Stacklet',
  tagline: 'Your local stack, one place.',

  /** Lowercase slug: IPC prefix, log prefix, generated-file markers, CLI name. */
  slug: 'stacklet',

  /** Pre-rename slug — migrations and parsing legacy configs only. */
  legacySlug: 'devmgr',
  /** Alternate legacy token (e.g. nginx comment markers). */
  legacySlugDash: 'dev-mgr',

  /** `%LOCALAPPDATA%\\{dataDirName}` runtime data folder. */
  dataDirName: 'stacklet',
  legacyDataDirName: 'devmgr',

  /** CLI binary name (`npm run stacklet`, `npx stacklet`). */
  cliName: 'stacklet',

  /** Electron preload `window` property exposed to the renderer. */
  windowApi: 'stacklet',

  /** IPC channel prefix (`stacklet:status`, …). */
  ipcPrefix: 'stacklet',

  /** Local HTTPS certificate authority common name (Windows cert store). */
  caCommonName: 'Stacklet Local CA',
  legacyCaCommonName: 'DevMgr Local CA',

  /** Shared leaf certificate CN (per-site names live in SAN). */
  leafCommonName: 'stacklet.local',
  legacyLeafCommonName: 'dev-mgr.local',

  /** Named pipe for the elevated helper (Windows). */
  helperPipe: '\\\\.\\pipe\\stacklet-helper',

  hostsMarkerBegin: '# BEGIN stacklet',
  hostsMarkerEnd: '# END stacklet',
} as const;

/** Console / log prefix, e.g. `[stacklet]`. */
export function logPrefix(): string {
  return `[${BRAND.slug}]`;
}

/** Comment header in generated service configs. */
export function generatedBy(feature: string): string {
  return `# Generated by ${BRAND.name} — ${feature}`;
}

/** Primary env var (`STACKLET_FOO`). */
export function envVar(suffix: string): string {
  return `${BRAND.slug.toUpperCase()}_${suffix}`;
}

/** Legacy env var (`DEVMGR_FOO`) — still read for compatibility. */
export function legacyEnvVar(suffix: string): string {
  return `DEVMGR_${suffix}`;
}

/** Read `STACKLET_*` with fallback to `DEVMGR_*`. */
export function readEnv(suffix: string): string | undefined {
  return process.env[envVar(suffix)] ?? process.env[legacyEnvVar(suffix)];
}

export function legacyHostsMarkers(): { begin: string; end: string } {
  return {
    begin: `# BEGIN ${BRAND.legacySlug}`,
    end: `# END ${BRAND.legacySlug}`,
  };
}

/** Matches nginx `http {}` include blocks from any branded build. */
export function nginxIncludeBlockRegex(): RegExp {
  const tokens = [BRAND.legacySlugDash, BRAND.slug, BRAND.legacySlug].join('|');
  return new RegExp(
    `\\n\\s*# (?:${tokens})\\s*\\n(?:\\s*include\\s+"[^"]+"\\s*;\\s*\\n)+`,
    'g',
  );
}

/** Leaf cert CN — use in TLS SAN lists and tests. */
export const LEAF_CN = BRAND.leafCommonName;

/** @deprecated Use {@link LEAF_CN} or {@link BRAND.leafCommonName}. */
export const DEV_MGR_LEAF_CN = LEAF_CN;
