import path from 'path';
import type { DevConfig, Site } from '../../config/types';
import { getFullChainCertPath, getLeafKeyPath, getLogsDir } from '../../shared/paths';
import { PHP_FASTCGI_PORT } from '../service-ports';

function q(p: string): string {
  return `"${path.resolve(p).replace(/\\/g, '/').replace(/"/g, '\\"')}"`;
}

function serverNames(site: Site): { name: string; aliases: string[] } {
  return { name: site.hostname, aliases: (site.aliases ?? []).filter(Boolean) };
}

/** PHP handler: proxy *.php to the FastCGI php-cgi (mod_proxy_fcgi). */
function phpHandler(phpPort: number): string {
  return `  <FilesMatch \\.php$>
    SetHandler "proxy:fcgi://127.0.0.1:${phpPort}"
  </FilesMatch>`;
}

function vhost(
  docRoot: string,
  names: { name: string; aliases: string[] },
  logName: string,
  ssl: { cert: string; key: string } | null,
  ports: { http: number; ssl: number },
  phpPort: number,
): string {
  const port = ssl ? ports.ssl : ports.http;
  const alias = names.aliases.length ? `\n  ServerAlias ${names.aliases.join(' ')}` : '';
  const sslBlock = ssl
    ? `\n  SSLEngine on\n  SSLCertificateFile ${q(ssl.cert)}\n  SSLCertificateKeyFile ${q(ssl.key)}`
    : '';
  return `<VirtualHost *:${port}>
  ServerName ${names.name}${alias}
  DocumentRoot ${q(docRoot)}
  DirectoryIndex index.php index.html${sslBlock}
  <Directory ${q(docRoot)}>
    Options Indexes FollowSymLinks
    AllowOverride All
    Require all granted
  </Directory>
${phpHandler(phpPort)}
  ErrorLog ${q(path.join(getLogsDir(), 'sites', logName, 'apache-error.log'))}
  CustomLog ${q(path.join(getLogsDir(), 'sites', logName, 'apache-access.log'))} common
</VirtualHost>`;
}

function siteBlocks(
  docRoot: string,
  names: { name: string; aliases: string[] },
  logName: string,
  cert: string,
  key: string,
  ports: { http: number; ssl: number },
  phpPort: number,
): string {
  return [
    vhost(docRoot, names, logName, null, ports, phpPort),
    vhost(docRoot, names, logName, { cert, key }, ports, phpPort),
  ].join('\n\n');
}

export function renderApacheVhosts(
  config: DevConfig,
  sites: Site[],
  phpPort: (site: Site) => number = () => PHP_FASTCGI_PORT,
): string {
  const cert = getFullChainCertPath();
  const key = getLeafKeyPath();
  const ports = { http: config.services.apache.port, ssl: config.services.apache.ssl_port };
  const header = '# Generated by Stacklet — Apache site vhosts (PHP via mod_proxy_fcgi)\n';

  const blocks: string[] = [];

  const pma = config.services.phpmyadmin;
  if (pma.enabled && pma.path) {
    blocks.push(
      siteBlocks(
        pma.path,
        { name: pma.hostname || 'phpmyadmin.test', aliases: [] },
        'phpmyadmin',
        cert,
        key,
        ports,
        PHP_FASTCGI_PORT,
      ),
    );
  }

  for (const site of sites.filter((s) => s.enabled !== false)) {
    blocks.push(
      siteBlocks(site.doc_root, serverNames(site), site.name, cert, key, ports, phpPort(site)),
    );
  }

  if (blocks.length === 0) return `${header}\n# No registered sites\n`;
  return `${header}\n${blocks.join('\n\n')}\n`;
}
